### ISSUE TITLE
Suggested method of installation does not work

### ISSUE THREAD

**Issue by jhennies** [ilastik/tiktorch#103]
We tried to install the tiktorch server the way it's described in the README, but this did not work:
- After installing the environment, `tiktorch-server` is not available (there is no such executable in bin).
- There is the exec `tiktorch` though.
- When executing it, the `grpc` package is missing.
- We have added it via `conda install -c conda-forge grpcio`
- Finally, the `tiktorch` command then runs, but throws a worning or something:
```
10310
Starting grpc server on 127.0.0.1:29500
E0313 10:32:25.536425704   10310 socket_utils_common_posix.cc:201] check for SO_REUSEPORT: {"created":"@1584091945.536417597","description":"SO_REUSEPORT unavailable on compiling system","file":"src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":169}
```

cc @constantinpape

**Comment by m-novikov** [comment]
It seems like conda picked up an older version of the tiktorch package from ilastik-forge. I'll remove obsolete packages, but in the meantime try to use the following command to create an environment:
```
conda create -n tiktorch-server-env -c ilastik-forge -c conda-forge -c pytorch "tiktorch>=20.3"
```

**Comment by m-novikov** [comment]
```
E0313 10:32:25.536425704   10310 socket_utils_common_posix.cc:201] check for SO_REUSEPORT: {"created":"@1584091945.536417597","description":"SO_REUSEPORT unavailable on compiling system","file":"src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":169}
```
This warning has no effect on functionality

**Comment by constantinpape** [comment]
Thanks @m-novikov. @jhennies could you please check again if this works for you when you set up a new environment?

**Comment by jhennies** [comment]
Thanks a lot @m-novikov! Works like a charm, both on my ubuntu laptop and on the centos vm @constantinpape

**Comment by constantinpape** [comment]
Thanks for checking.
