### ISSUE TITLE
Reloading data after loading model gives a silent crash on ilastik side

### ISSUE THREAD

**Issue by vzinche** [ilastik/tiktorch#121]
![reloading_data_crash](https://user-images.githubusercontent.com/32451366/86477259-53d53c80-bd48-11ea-8d9b-ec9903c3a9ed.gif)

`ERROR 2020-07-03 16:13:26,723 classifier 14043 140383719229184 predict tile shape: (1, 256, 256, 1) (axistags: z y x c)
ERROR 2020-07-03 16:13:26,725 classifier 14043 140383719229184 Predict call failed
Traceback (most recent call last):
  File "/home/zinchenk/software/ilastik-1.4.0b5-Linux/ilastik-meta/ilastik/lazyflow/operators/tiktorch/classifier.py", line 161, in predict
    resp = resp.result()
  File "/home/zinchenk/software/ilastik-1.4.0b5-Linux/lib/python3.7/site-packages/grpc/_channel.py", line 295, in result
    raise self
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.FAILED_PRECONDITION
	details = "model-session with id d9bfef0ccefc4c198ef713e486719036 doesn't exist"
	debug_error_string = "{"created":"@1593785606.725321260","description":"Error received from peer ipv4:127.0.0.1:5567","file":"src/core/lib/surface/call.cc","file_line":1052,"grpc_message":"model-session with id d9bfef0ccefc4c198ef713e486719036 doesn't exist","grpc_status":9}"`

**Comment by JackieZhai** [comment]
Similar issue here from `Beta Version 1.4.1b13 (13. December 2023)` at `Apple Silicon (arm64), OSX`:
```
Failed to initialize model:
 <class 'grpc._channel._InactiveRpcError'> <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: "
	debug_error_string = "{"created":"@1703820297.823562000","description":"Error received from peer ipv4:127.0.0.1:58150","file":"src/core/lib/surface/call.cc","file_line":1070,"grpc_message":"Exception calling application: ","grpc_status":2}"
>
```
<img width="543" alt="image" src="https://github.com/ilastik/tiktorch/assets/23720927/70205190-25f1-4261-9d9f-e3be303dc85e">

**Comment by k-dominik** [comment]
Hi @JackieZhai,

thank you for checking this issue. Did you arrive the same way at this error as the original author? I tried reproducing it (by removing and adding data) and this works without issues now. If you arrived at this error in any other way, it would be very valuable to know. Or anything else that can help reproduce the problem.

Cheers
Dominik

**Comment by JackieZhai** [comment]
Hi @k-dominik,

It seem that my way is not as same as @vzinche's.

The way I tried:
1. Select "Neural Network Classification (Local)",
2. Import a sample 3D `.tif` file,
3. Choose NN model from [https://bioimage.io/#/?tags=ilastik&id=10.5281%2Fzenodo.5874741](https://bioimage.io/#/?tags=ilastik&id=10.5281%2Fzenodo.5874741) by downloaded `.zip` file for ilastik,
4. Click the green "->" button, then the problem raised.

Thanks for your help!

Best wishes,
Jackie

**Comment by k-dominik** [comment]
Hi @JackieZhai, thank you very much for the clarification. I suspect strongly that this is the same issue as https://github.com/ilastik/ilastik/issues/2788. I will close this issue and open a new one here in the tiktorch repository.
