### ISSUE TITLE
Several pre-processing issues

### ISSUE THREAD

**Issue by constantinpape** [ilastik/tiktorch#184]
During the course last week we found several issues with preprocessing:
- Preprocessing operations do not always return float32. I have hot-fixed this for the example models. Also, #180 might fix this for zero-mean-unit-variance, but it would be good to fix this for all preprocessing. 
- Pre-processing yields incorrect results for wrong image dtype, for example https://bioimage.io/#/?id=10.5072%2Fzenodo.881973 yields correct results for uint8 inputs, but incorrect ones for uint16
- Would be good to have more CI for this...

**Comment by m-novikov** [comment]
Maybe cast should be injected in `make_preprocessing`  as a last step, to ensure that the type is the same after all the steps.

It's also possible to inject first step, but it's unclear what method should be used for lossy conversion and how it should be communicated to user.

**Comment by k-dominik** [comment]
that's an interesting problem. Reading this it looks almost like one would have to enforce/encourage/recommend usage of preprocessing that does not _directly_ introduce such issues. Like always doing some kind of normalization (range, and dtype). How limiting would this actually be for network developers?

**Comment by constantinpape** [comment]
> What is the expectancy when coming with `uint16` instead of `uint8`?

One option would be to have implicit preprocessing that transforms to the specified datatype and data range. For sure this has also some pitfalls.
I think we have these options:
- Add the implicit preprocessing
- Provide a warning if the data provided does not match the data specified

This could also be combined, i.e. warn if the data doesn't match and then transform it.

**Comment by FynnBe** [comment]
maybe we could mandate in the spec that every preprocessing includes a normalization or  a type casting (and no value tranforming preprocessing steps preceding it)?

**Comment by m-novikov** [comment]
I don't think that this problem is solvable with the spec only. It's a runtime issue where we receive the data with insufficient information about the properties of the incoming image. 
Maybe this kind of normalization should be prompted on ilastik side so users can decide what to do with it.
Especially considering that we only see one block here.

**Comment by constantinpape** [comment]
> I don't think that this problem is solvable with the spec only. It's a runtime issue where we receive the data with insufficient information about the properties of the incoming image.
> Maybe this kind of normalization should be prompted on ilastik side so users can decide what to do with it.

I agree, we will most likely not be able to solve all corner cases, but having something that works most of the time (and issues a warning if it's unclear if the preprocessing will do the right thing) would already be quite helpful.
Enabling user preprocessing would of course be good, but I am not quite sure what's the best strategy for this.

> Especially considering that we only see one block here.

That's another important point, which I forgot to bring up in the initial issue: we need to enable per data-set (i.e. image or volume) preprocessing for zero-mean-unit-variance, because the values estimated from a single block are too noisy.

> I'm not sure what CI would help there.

@k-dominik: I just saw your comment here. And I was not quite clear in my initial description: there were some cases in which the preprocessing returned a non float32 value and for which applying the model then failed.
(I have added casting to float32 in the model as a hotfix for this, but this is ofc not something we can rely on).
These cases could be caught by CI; there could be CI that ensures float32 output for various inputs.

**Comment by k-dominik** [comment]
Current behavior is up to spec (as in not specified what should happen): https://github.com/bioimage-io/spec-bioimage-io/blob/main/supported_formats_and_operations.md#preprocessing

I propose we first specify expectations of preprocessing in terms of dtypes (in/out) and then try to fix the implementation and test for those specifications.

**Comment by constantinpape** [comment]
> Current behavior is up to spec (as in not specified what should happen): https://github.com/bioimage-io/spec-bioimage-io/blob/main/supported_formats_and_operations.md#preprocessing

Indeed, it's not specified in the spec; but at least for all preprocessing it should return float32; this was long discussed in one of the meetings quite a while ago already.

**Comment by k-dominik** [comment]
closing this, since preprocessing is now part of `bioimageio.core`
